//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLegadoEducativo01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/WSLEClientesPotenciales/WSInsertaClientePotencial" +
            ".asmx")]
        public string WebClientesPotencialesLEProp_WSInsertaClientePotencial_WSInsertaClientePotencial {
            get {
                return ((string)(this["WebClientesPotencialesLEProp_WSInsertaClientePotencial_WSInsertaClientePotencial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/WSUDEM/WSConsUsuext.asmx")]
        public string WebClientesPotencialesLEProp_WSConsUsuext_WSConsUsuext {
            get {
                return ((string)(this["WebClientesPotencialesLEProp_WSConsUsuext_WSConsUsuext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/WSUDEM/WSInsUsuarioExterno.asmx")]
        public string WebClientesPotencialesLEProp_WSInsUsuarioExterno_WSInsUsuarioExterno {
            get {
                return ((string)(this["WebClientesPotencialesLEProp_WSInsUsuarioExterno_WSInsUsuarioExterno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/WSUDEM/WSConClientePotencial.asmx")]
        public string WebClientesPotencialesLEProp_WSConClientePotencial_WSConClientePotencial {
            get {
                return ((string)(this["WebClientesPotencialesLEProp_WSConClientePotencial_WSConClientePotencial"]));
            }
        }
    }
}
