//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo01.WS_LE_ConsTestimonios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsTestimoniosSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsTestimonios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsTestimoniosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsTestimonios() {
            this.Url = global::WebLegadoEducativo01.Properties.Settings.Default.WebLegadoEducativo01_WS_LE_ConsTestimonios_WS_LE_ConsTestimonios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsTestimoniosCompletedEventHandler ConsTestimoniosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsTestimonios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsTestimonios[] ConsTestimonios(string new_visibleenweb) {
            object[] results = this.Invoke("ConsTestimonios", new object[] {
                        new_visibleenweb});
            return ((CsTestimonios[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsTestimoniosAsync(string new_visibleenweb) {
            this.ConsTestimoniosAsync(new_visibleenweb, null);
        }
        
        /// <remarks/>
        public void ConsTestimoniosAsync(string new_visibleenweb, object userState) {
            if ((this.ConsTestimoniosOperationCompleted == null)) {
                this.ConsTestimoniosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsTestimoniosOperationCompleted);
            }
            this.InvokeAsync("ConsTestimonios", new object[] {
                        new_visibleenweb}, this.ConsTestimoniosOperationCompleted, userState);
        }
        
        private void OnConsTestimoniosOperationCompleted(object arg) {
            if ((this.ConsTestimoniosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsTestimoniosCompleted(this, new ConsTestimoniosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsTestimonios {
        
        private string new_testimonioslegadoeducativoidField;
        
        private string new_mensajeField;
        
        private string new_nombreusuariotestimonioField;
        
        private string new_visibleenwebField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string new_testimonioslegadoeducativoid {
            get {
                return this.new_testimonioslegadoeducativoidField;
            }
            set {
                this.new_testimonioslegadoeducativoidField = value;
            }
        }
        
        /// <remarks/>
        public string new_mensaje {
            get {
                return this.new_mensajeField;
            }
            set {
                this.new_mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string new_nombreusuariotestimonio {
            get {
                return this.new_nombreusuariotestimonioField;
            }
            set {
                this.new_nombreusuariotestimonioField = value;
            }
        }
        
        /// <remarks/>
        public string new_visibleenweb {
            get {
                return this.new_visibleenwebField;
            }
            set {
                this.new_visibleenwebField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsTestimoniosCompletedEventHandler(object sender, ConsTestimoniosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsTestimoniosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsTestimoniosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsTestimonios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsTestimonios[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591